Is APP market competitive? Looking at millions of APPs in the market, the answer seems to be yes. Then if free competition promises efficiency and the best of consumer welfare, as most classical economic theory suggests, why we bother worrying APPs excessively request our private data? In this study we seek to answer a funndamental question in the APP market: would competition reduces APP vendor's incentive to request customer information?

According to APP Annie's 2016 annual report\footnote{https://www.appannie.com/en/insights/market-data/app-annie-2016-retrospective/}, Android App market is now offering almost 3 million APPs and this number on APP Store is more than 2 million. Among these APPs, more than 80\% Android APPs are free and nearly 70\% iphone APPs are free. These APP vendors, though don't charge money from customers directly, could base their profit on collecting customer data, for example, consumer preference information would allow firms to make better advertising strategy, consumers' location information and navigation history enable firms to conduct precise marketing.

On the other hand, consumer's concerns about the security of personal data on smart phones are at an all-time high. People worry, for example, misuse of the information in address book which would reveal trade secrets, or, leakage of daily routine stored in the calendar which might be shared with criminals. In 2012, Grace et al. conducted an thorough investigation which confirmed that many App vendors did collect user private information which is hard to justify.  

According to classical economic theory, scholars widely acknowledge that insufficient competition would result in excessive prices and loss of consumer welfare. Ever since, policies that aim to promote competition have become an instrument for generating better social outcomes by directly influencing market structure. Similarly, by drawing an analogy between private data and price charged from APP vendors, one might automatically expect promoting APP competition would in consumer's interests in alleviate firm's desire for more customer data.

However, before directly borrowing the idea of price competition theory, one needs to note some unique characteristics of APP market. From firm's side, APPs are highly differentiated. It may take big companies such as Facebook, Google millions of dollars to develop an APP but an amateur can develop a simple one in just a few days. And the cost mainly costs from developing, meaning once developed, they are nearly free to reproduce or distribute. From user's side, APP marketplace allows easy comparison and download, so the search cost is low. And most of APPs are free, we choose APPs based on functionality and privacy preference.

Contrary to what convention wisdom would suggest, we surprisingly find advocating competition would NOT reduce firm's intention to request customer data by incorporating these characteristics into analysis. We testify this conjecture through both theoretical and empirical analysis. On doing this, we propose a APP competition model which can explain the structure of APP market and possibly be applied to evaluate policy issues in APP market. Empirical evidence turns out to support the theoretical analysis. In the extension of this paper, we use this model to further evaluate the maximum privacy requirements standard policy.

Literature Review
